version: "3"

services:
  cdu:
    build: cdu
    ports:
      - "8080:8080"
    volumes:
      - ${DATA_DIR_HOST}:/data
    environment:
      - DATA_DIR=/data
  
  frontend:
    build: frontend
    ports:
      - "3000:3000"
    depends_on:
      - cdu