name: CI-CDU

on:
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/CI-CDU.yml'
      - 'cdu/**'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/CI-CDU.yml'
      - 'cdu/**'
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cdu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --issues-exit-code=1 --timeout=10m
          working-directory: cdu
      
      - name: Build
        run: go build ./...
      
      - name: Test
        run: go test ./... -count=1

      - name: Test Integration 
        if: github.event_name != 'workflow_dispatch' || github.event.inputs.run_integration_tests == 'true'
        run: go test ./... -count=1 -tags=integration
        timeout-minutes: 60 

      - name: Semgrep
        run: docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep ci --config "p/golang" --no-suppress-errors